language: ruby
cache: bundler
bundler_args: --without benchmarks tools
rvm:
  - ruby-head
  - 2.5
  - 2.4
  - 2.3
  - 2.2
  - 2.1
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: 2.1
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/680e86d98056f2ae2fd7
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
